project:
  type: website

date-format: iso
author: "Márk Sági-Kazár"

format:
  revealjs:
    # mermaid-format: svg
    transition: slide
    controls: true
    controls-layout: bottom-right
    template-partials:
      - resources/templates/revealjs/title-slide.html
