timeline
    Aug 10: BUSL Announcement
    Aug 11: "opentf" org on GH was created
    Aug 15: OpenTF manifesto
    Aug 25: OpenTF fork announcement
    Sep 20: LF launches OpenTofu
    Oct 4: First alpha release
