direction: down

Vault: {
  label: Vault
  shape: image
  icon: https://www.svgrepo.com/download/448679/vault.svg
}

AWSSM: {
  label: AWS Secrets Manager
  shape: image
  icon: https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAWS-Secrets-Manager.svg
}

GCPSM: {
  label: GCP Secret Manager
  shape: image
  icon: https://www.svgrepo.com/download/375492/secret-manager.svg
}

AzureKeyVault: {
  label: Azure Key Vault
  shape: image
  icon: https://icons.terrastruct.com/azure%2FSecurity%20Service%20Color%2FKey%20Vaults.svg
}

BVSecretSync: {
  label: Bank-Vaults Secret Sync
  shape: image
  icon: https://raw.githubusercontent.com/bank-vaults/bank-vaults.dev/main/assets/icons/logo.svg
}

Vault -> BVSecretSync
AWSSM -> BVSecretSync
GCPSM -> BVSecretSync
AzureKeyVault -> BVSecretSync

ClusterA: {
  label: Cluster A
  icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg

  LocalA: Local Vault
  WorkloadA: Workload

  LocalA -> WorkloadA
}

ClusterB: {
  label: Cluster B
  icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg

  LocalB: Local Vault
  WorkloadB: Workload

  LocalB -> WorkloadB
}

ClusterC: {
  label: Cluster C
  icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg

  LocalC: Local Vault
  WorkloadC: Workload

  LocalC -> WorkloadC
}

BVSecretSync -> ClusterA.LocalA: Sync
BVSecretSync -> ClusterB.LocalB: Sync
BVSecretSync -> ClusterC.LocalC: Sync
