%%{init: { 'logLevel': 'debug', 'theme': 'default' , 'themeVariables': {
            'cScale0': '#0c1d59',
            'cScale1': '#6273b1',
            'cScale2': '#80b9e2',
            'cScale3': '#4d8ec1',
            'cScale4': '#a6aad2'
    } } }%%
timeline
    title History of Banzai Cloud
    2017 : Idea
         : Company
    2018 : First seed round
         : New CEO
    2019 : First release
         : First customer engagement
    2020 : First paying customer
         : Acquisition
    2021 : TOB
